profile::wordpress::docs::admin_email: infrastructure-team@jquery.com
profile::wordpress::docs::builder_email: infrastructure-team+builder@jquery.com
profile::wordpress::docs::robots_txt_deny_all: true
profile::wordpress::docs::enable_object_cache: true
profile::wordpress::docs::wordpress_version: ~

profile::tarsnap::enabled: false

profile::certbot::certificates:
  wordpress:
    domains:
      - "%{::facts.fqdn}"
      - stage.api.jquery.com
      - stage.api.jquerymobile.com
      - stage.api.jqueryui.com
      - stage.brand.jquery.org
      - stage.contribute.jquery.org
      - stage.jquery.com
      - stage.jquery.org
      - stage.jquerymobile.com
      - stage.jqueryui.com
      - stage.learn.jquery.com
      - stage.meetings.jquery.org
      - stage.releases.jquery.com
