profile::certbot::certificates:
  blogs:
    domains:
      - "%{::facts.fqdn}"

profile::wordpress::blogs::admin_email: infrastructure-team@jquery.com
profile::wordpress::blogs::wordpress_version: ~
profile::wordpress::blogs::sites:
  jquery:
    host: blog.jquery.com
    site_name: Official jQuery Blog
    active_theme: jquery.com
    certificate: blogs
  jquerymobile:
    host: blog.jquerymobile.com
    site_name: jQuery Mobile
    active_theme: jquerymobile.com
    certificate: blogs
  jqueryui:
    host: blog.jqueryui.com
    site_name: jQuery UI Blog
    active_theme: jqueryui.com
    certificate: blogs
    # for whatever reason, the jqueryui blog has a different URL structure
    # compared to other blogs have
    permalink_structure: '/%year%/%monthnum%/%postname%/'
