profile::miscweb::podcast_vhost: podcast.jquery.com

profile::miscweb::default_certificate: miscweb

profile::miscweb::redirects:
  brand.jquery.com:
    target: https://brand.jquery.org
    mode: prefix
    certificate: miscweb-a
  contribute.jquery.com:
    target: https://contribute.jquery.org
    mode: prefix
    certificate: miscweb-a
  dev.jqueryui.com:
    target: https://bugs.jqueryui.com
    mode: prefix
    certificate: miscweb-a
  download.jquery.com:
    target: https://jquery.com/download/
    mode: root
    certificate: miscweb-a
  download.jquerymobile.com:
    target: https://jquerymobile.com/download/
    mode: root
    certificate: miscweb-a
  events.jquery.com:
    target: https://openjsf.org/
    mode: root
    certificate: miscweb-a
  events.jquery.org:
    target: https://openjsf.org/
    mode: root
    certificate: miscweb-a
  irc.jquery.com:
    target: https://irc.jquery.org/
    mode: root
    certificate: miscweb-a
  learn.jqueryui.com:
    target: https://learn.jquery.com/jquery-ui/
    mode: root
    certificate: miscweb-a
  meetups.jquery.com:
    target: https://jquery.com/meetups/
    mode: root
    certificate: miscweb-a
  meetups.jquery.org:
    target: https://jquery.com/meetups/
    mode: root
    certificate: miscweb-a
  # "Try jQuery" is no more.
  # https://blog.jquery.com/2013/02/22/try-jquery-interactive-course/
  try.jquery.com:
    target: https://learn.jquery.com/
    mode: root
    certificate: miscweb-a
  swarm.jquery.com:
    target: https://swarm.jquery.org
    mode: prefix
    certificate: miscweb-a
  ui.jquery.com:
    target: https://jqueryui.com
    mode: prefix
    certificate: miscweb-a
  # Gitview was a file browser for release artefacts, superseded by the releases docsite.
  # https://github.com/jquery/infrastructure/issues/503
  view.jquery.com:
    target: https://releases.jquery.com/jquery/
    mode: root
    certificate: miscweb-a
  view.jquery.org:
    target: https://releases.jquery.com/jquery/
    mode: root
    certificate: miscweb-a
  view.jquerymobile.com:
    target: https://releases.jquery.com/mobile/
    mode: root
    certificate: miscweb-a
  view.jqueryui.com:
    target: https://releases.jquery.com/ui/
    mode: root
    certificate: miscweb-a
  www.jquery.com:
    target: https://jquery.com
    mode: prefix
    certificate: miscweb-a
  www.jquery.org:
    target: https://jquery.org
    mode: prefix
    certificate: miscweb-a
  www.jquerymobile.com:
    target: https://jquerymobile.com
    mode: prefix
    certificate: miscweb-a
  www.jqueryui.com:
    target: https://jqueryui.com
    mode: prefix
    certificate: miscweb-a
