profile::certbot::certificates:
  miscweb:
    domains:
      - "%{::facts.fqdn}"
      - podcast.jquery.com
      - demos.jquerymobile.com
profile::miscweb::default_certificate: miscweb

profile::miscweb::sites:
  demos.jquerymobile.com:
    repository:
      name: jquery/demos.jquerymobile.com
      branch: main
    allow_php: true
  podcast.jquery.com:
    repository:
      name: jquery/podcast.jquery.com
      branch: main
    webroot: /build_production
    extra_config: |
      # Compatibility with http://feeds.feedburner.com/jQueryPodcastShowNotes
      rewrite ^/feed/?$ /feed/jQueryPodcastShowNotes.xml permanent;
  themeroller.jquerymobile.com:
    repository:
      name: jquery/themeroller.jquerymobile.com
      branch: main
    allow_php: true
    extra_config: |
      location ~ ^/zips/(?<name>.*)\.zip {
        alias /var/cache/themeroller-zip/$name.zip;
      }
    php_env:
      THEMEROLLER_ZIPDIR: /var/cache/themeroller-zip

profile::miscweb::redirects:
  # css-chassis.com
  css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  perf.css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  view.css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  www.css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  # css-chassis.org
  css-chassis.org:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  www.css-chassis.org:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  # js.foundation
  js.foundation:
    target: https://openjsf.org
    mode: root
  www.js.foundation:
    target: https://openjsf.org
    mode: root
  cla.js.foundation:
    target: https://cla.openjsf.org
    mode: root
  # jquery.com
  brand.jquery.com:
    target: https://brand.jquery.org
    mode: prefix
    certificate: miscweb-a
  contribute.jquery.com:
    target: https://contribute.jquery.org
    mode: prefix
    certificate: miscweb-a
  dev.jqueryui.com:
    target: https://bugs.jqueryui.com
    mode: prefix
    certificate: miscweb-a
  download.jquery.com:
    target: https://jquery.com/download/
    mode: root
    certificate: miscweb-a
  download.jquerymobile.com:
    target: https://jquerymobile.com/download/
    mode: root
    certificate: miscweb-a
  events.jquery.com:
    target: https://openjsf.org/
    mode: root
    certificate: miscweb-a
  irc.jquery.com:
    target: https://irc.jquery.org/
    mode: root
    certificate: miscweb-a
  meetups.jquery.com:
    target: https://jquery.com/meetups/
    mode: root
    certificate: miscweb-a
  try.jquery.com:
    # "Try jQuery" is no more.
    # https://blog.jquery.com/2013/02/22/try-jquery-interactive-course/
    target: https://learn.jquery.com/
    mode: root
    certificate: miscweb-a
  swarm.jquery.com:
    target: https://swarm.jquery.org
    mode: prefix
    certificate: miscweb-a
  ui.jquery.com:
    target: https://jqueryui.com
    mode: prefix
    certificate: miscweb-a
  view.jquery.com:
    # Gitview was a file browser for release artefacts, superseded by the releases docsite.
    # https://github.com/jquery/infrastructure/issues/503
    target: https://releases.jquery.com/jquery/
    mode: root
    certificate: miscweb-a
  www.jquery.com:
    target: https://jquery.com
    mode: prefix
    certificate: miscweb-a
  # jqueryui.com
  learn.jqueryui.com:
    target: https://learn.jquery.com/jquery-ui/
    mode: root
    certificate: miscweb-a
  view.jqueryui.com:
    target: https://releases.jquery.com/ui/
    mode: root
    certificate: miscweb-a
  wiki.jqueryui.com:
    target: https://jqueryui.pbworks.com
    mode: prefix
    certificate: miscweb-a
  www.jqueryui.com:
    target: https://jqueryui.com
    mode: prefix
    certificate: miscweb-a
  # jquerymobile.com
  jquerymobile.net:
    target: https://jquerymobile.com
    mode: root
    certificate: miscweb-a
  jquerymobile.org:
    target: https://jquerymobile.com
    mode: root
    certificate: miscweb-a
  view.jquerymobile.com:
    target: https://releases.jquery.com/mobile/
    mode: root
    certificate: miscweb-a
  www.jquerymobile.com:
    target: https://jquerymobile.com
    mode: prefix
    certificate: miscweb-a
  # jquery.org
  events.jquery.org:
    target: https://openjsf.org/
    mode: root
    certificate: miscweb-a
  meetups.jquery.org:
    target: https://jquery.com/meetups/
    mode: root
    certificate: miscweb-a
  view.jquery.org:
    target: https://releases.jquery.com/jquery/
    mode: root
    certificate: miscweb-a
  www.jquery.org:
    target: https://jquery.org
    mode: prefix
    certificate: miscweb-a
