profile::testswarm::public_host_name: "swarm.jquery.org"

profile::testswarm::browserstack::ensure: present
profile::testswarm::server::cleanup_ensure: present

profile::testswarm::server::settings::user_agents:
  chrome_90:
    browserFamily: Chrome
    browserMajor: '90'
  chrome_91:
    browserFamily: Chrome
    browserMajor: '91'
  chrome_92:
    browserFamily: Chrome
    browserMajor: '92'
  chrome_93:
    browserFamily: Chrome
    browserMajor: '93'
  chrome_94:
    browserFamily: Chrome
    browserMajor: '94'
  chrome_95:
    browserFamily: Chrome
    browserMajor: '95'
  chrome_96:
    browserFamily: Chrome
    browserMajor: '96'
  chrome_97:
    browserFamily: Chrome
    browserMajor: '97'
  chrome_98:
    browserFamily: Chrome
    browserMajor: '98'
  chrome_99:
    browserFamily: Chrome
    browserMajor: '99'
  chrome_102:
    browserFamily: Chrome
    browserMajor: '102'
  chrome_103:
    browserFamily: Chrome
    browserMajor: '103'
  chrome_104:
    browserFamily: Chrome
    browserMajor: '104'
  chrome_105:
    browserFamily: Chrome
    browserMajor: '105'
  chrome_106:
    browserFamily: Chrome
    browserMajor: '106'
  chrome_107:
    browserFamily: Chrome
    browserMajor: '107'
  chrome_108:
    browserFamily: Chrome
    browserMajor: '108'
  chrome_109:
    browserFamily: Chrome
    browserMajor: '109'
  chrome_110:
    browserFamily: Chrome
    browserMajor: '110'
  chrome_111:
    browserFamily: Chrome
    browserMajor: '111'
  chrome_112:
    browserFamily: Chrome
    browserMajor: '112'
  chrome_113:
    browserFamily: Chrome
    browserMajor: '113'
  chrome_114:
    browserFamily: Chrome
    browserMajor: '114'
  chrome_115:
    browserFamily: Chrome
    browserMajor: '115'
  chrome_116:
    browserFamily: Chrome
    browserMajor: '116'
  chrome_117:
    browserFamily: Chrome
    browserMajor: '117'
  firefox_48:
    browserFamily: Firefox
    browserMajor: '48'
  firefox_60:
    browserFamily: Firefox
    browserMajor: '60'
  firefox_78:
    browserFamily: Firefox
    browserMajor: '78'
  firefox_88:
    browserFamily: Firefox
    browserMajor: '88'
  firefox_89:
    browserFamily: Firefox
    browserMajor: '89'
  firefox_90:
    browserFamily: Firefox
    browserMajor: '90'
  firefox_91:
    browserFamily: Firefox
    browserMajor: '91'
  firefox_92:
    browserFamily: Firefox
    browserMajor: '92'
  firefox_93:
    browserFamily: Firefox
    browserMajor: '93'
  firefox_94:
    browserFamily: Firefox
    browserMajor: '94'
  firefox_95:
    browserFamily: Firefox
    browserMajor: '95'
  firefox_96:
    browserFamily: Firefox
    browserMajor: '96'
  firefox_97:
    browserFamily: Firefox
    browserMajor: '97'
  firefox_98:
    browserFamily: Firefox
    browserMajor: '98'
  firefox_100:
    browserFamily: Firefox
    browserMajor: '100'
  firefox_101:
    browserFamily: Firefox
    browserMajor: '101'
  firefox_102:
    browserFamily: Firefox
    browserMajor: '102'
  firefox_103:
    browserFamily: Firefox
    browserMajor: '103'
  firefox_104:
    browserFamily: Firefox
    browserMajor: '104'
  firefox_105:
    browserFamily: Firefox
    browserMajor: '105'
  firefox_106:
    browserFamily: Firefox
    browserMajor: '106'
  firefox_107:
    browserFamily: Firefox
    browserMajor: '107'
  firefox_108:
    browserFamily: Firefox
    browserMajor: '108'
  firefox_109:
    browserFamily: Firefox
    browserMajor: '109'
  firefox_110:
    browserFamily: Firefox
    browserMajor: '110'
  firefox_111:
    browserFamily: Firefox
    browserMajor: '111'
  firefox_112:
    browserFamily: Firefox
    browserMajor: '112'
  firefox_113:
    browserFamily: Firefox
    browserMajor: '113'
  firefox_114:
    browserFamily: Firefox
    browserMajor: '114'
  firefox_115:
    browserFamily: Firefox
    browserMajor: '115'
  firefox_116:
    browserFamily: Firefox
    browserMajor: '116'
  firefox_117:
    browserFamily: Firefox
    browserMajor: '117'
  ie_6:
    browserFamily: IE
    browserMajor: '6'
  ie_7:
    browserFamily: IE
    browserMajor: '7'
  ie_8:
    browserFamily: IE
    browserMajor: '8'
  ie_9:
    browserFamily: IE
    browserMajor: '9'
  ie_10:
    browserFamily: IE
    browserMajor: '10'
  ie_11:
    browserFamily: IE
    browserMajor: '11'
  edge_18:
    browserFamily: Edge
    browserMajor: '18'
  edge_90:
    browserFamily: Edge
    browserMajor: '90'
  edge_91:
    browserFamily: Edge
    browserMajor: '91'
  edge_92:
    browserFamily: Edge
    browserMajor: '92'
  edge_93:
    browserFamily: Edge
    browserMajor: '93'
  edge_94:
    browserFamily: Edge
    browserMajor: '94'
  edge_95:
    browserFamily: Edge
    browserMajor: '95'
  edge_96:
    browserFamily: Edge
    browserMajor: '96'
  edge_97:
    browserFamily: Edge
    browserMajor: '97'
  edge_98:
    browserFamily: Edge
    browserMajor: '98'
  edge_99:
    browserFamily: Edge
    browserMajor: '99'
  edge_101:
    browserFamily: Edge
    browserMajor: '101'
  edge_102:
    browserFamily: Edge
    browserMajor: '102'
  edge_103:
    browserFamily: Edge
    browserMajor: '103'
  edge_104:
    browserFamily: Edge
    browserMajor: '104'
  edge_105:
    browserFamily: Edge
    browserMajor: '105'
  edge_106:
    browserFamily: Edge
    browserMajor: '106'
  edge_107:
    browserFamily: Edge
    browserMajor: '107'
  edge_108:
    browserFamily: Edge
    browserMajor: '108'
  edge_109:
    browserFamily: Edge
    browserMajor: '109'
  edge_110:
    browserFamily: Edge
    browserMajor: '110'
  edge_111:
    browserFamily: Edge
    browserMajor: '111'
  edge_112:
    browserFamily: Edge
    browserMajor: '112'
  edge_113:
    browserFamily: Edge
    browserMajor: '113'
  edge_114:
    browserFamily: Edge
    browserMajor: '114'
  edge_115:
    browserFamily: Edge
    browserMajor: '115'
  edge_116:
    browserFamily: Edge
    browserMajor: '116'
  opera_76:
    browserFamily: Opera
    browserMajor: '76'
  opera_77:
    browserFamily: Opera
    browserMajor: '77'
  opera_78:
    browserFamily: Opera
    browserMajor: '78'
  opera_79:
    browserFamily: Opera
    browserMajor: '79'
  opera_80:
    browserFamily: Opera
    browserMajor: '80'
  opera_81:
    browserFamily: Opera
    browserMajor: '81'
  opera_82:
    browserFamily: Opera
    browserMajor: '82'
  opera_83:
    browserFamily: Opera
    browserMajor: '83'
  opera_84:
    browserFamily: Opera
    browserMajor: '84'
  opera_87:
    browserFamily: Opera
    browserMajor: '87'
  opera_88:
    browserFamily: Opera
    browserMajor: '88'
  opera_89:
    browserFamily: Opera
    browserMajor: '89'
  opera_90:
    browserFamily: Opera
    browserMajor: '90'
  opera_91:
    browserFamily: Opera
    browserMajor: '91'
  opera_92:
    browserFamily: Opera
    browserMajor: '92'
  opera_93:
    browserFamily: Opera
    browserMajor: '93'
  opera_94:
    browserFamily: Opera
    browserMajor: '94'
  opera_95:
    browserFamily: Opera
    browserMajor: '95'
  opera_96:
    browserFamily: Opera
    browserMajor: '96'
  opera_97:
    browserFamily: Opera
    browserMajor: '97'
  opera_98:
    browserFamily: Opera
    browserMajor: '98'
  opera_99:
    browserFamily: Opera
    browserMajor: '99'
  opera_100:
    browserFamily: Opera
    browserMajor: '100'
  opera_101:
    browserFamily: Opera
    browserMajor: '101'
  opera_102:
    browserFamily: Opera
    browserMajor: '102'
  safari_5_1:
    browserFamily: Safari
    browserMajor: '5'
    browserMinor: '1'
  safari_6:
    browserFamily: Safari
    browserMajor: '6'
  safari_7:
    browserFamily: Safari
    browserMajor: '7'
  safari_8:
    browserFamily: Safari
    browserMajor: '8'
  safari_9:
    browserFamily: Safari
    browserMajor: '9'
  safari_10:
    browserFamily: Safari
    browserMajor: '10'
  safari_11:
    browserFamily: Safari
    browserMajor: '11'
  safari_12:
    browserFamily: Safari
    browserMajor: '12'
  safari_13:
    browserFamily: Safari
    browserMajor: '13'
  safari_14:
    browserFamily: Safari
    browserMajor: '14'
  safari_15:
    browserFamily: Safari
    browserMajor: '15'
  safari_16:
    browserFamily: Safari
    browserMajor: '16'
  safari_17:
    browserFamily: Safari
    browserMajor: '17'
  android_4_0:
    browserFamily: Android
    osFamily: Android
    osMajor: '4'
    osMinor: '0'
  android_4_1:
    browserFamily: Android
    osFamily: Android
    osMajor: '4'
    osMinor: '1'
  android_4_2:
    browserFamily: Android
    osFamily: Android
    osMajor: '4'
    osMinor: '2'
  android_4_3:
    browserFamily: Android
    osFamily: Android
    osMajor: '4'
    osMinor: '3'
  android_8_0:
    browserFamily: Chrome Mobile
    osFamily: Android
    osMajor: '8'
    osMinor: '0'
  android_12:
    browserFamily: Chrome Mobile
    osFamily: Android
    osMajor: '12'
  android_14:
    browserFamily: Chrome Mobile
    osFamily: Android
    osMajor: '12'
    deviceFamily: Google Pixel 8 Pro
  iphone-ios_7_0:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '7'
    osMinor: '0'
  iphone-ios_8_3:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '8'
    osMinor: '3'
  iphone-ios_9_3:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '9'
    osMinor: '3'
  iphone-ios_10:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '10'
  iphone-ios_11:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '11'
  iphone-ios_12:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '12'
  iphone-ios_13:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '13'
  iphone-ios_14:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '14'
  iphone-ios_15:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '15'
  iphone-ios_16:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '16'
  iphone-ios_17:
    deviceFamily: iPhone
    osFamily: iOS
    osMajor: '17'

profile::testswarm::server::settings::browser_sets:
  jquery:
    - chrome_116
    - chrome_117
    #- android_12
    - edge_115
    - edge_116
    - firefox_115
    - firefox_116
    - firefox_117
    - ie_11
    - opera_102
    - safari_16
    - safari_17
    - iphone-ios_15
    - iphone-ios_16
    - iphone-ios_17
  jquery-3:
    - chrome_116
    - chrome_117
    #- android_12
    - edge_18
    - edge_115
    - edge_116
    - firefox_48
    - firefox_60
    - firefox_78
    - firefox_91
    - firefox_102
    - firefox_115
    - firefox_116
    - firefox_117
    - ie_9
    - ie_10
    - ie_11
    - opera_102
    - safari_16
    - safari_17
    - iphone-ios_8_3
    - iphone-ios_9_3
    - iphone-ios_10
    - iphone-ios_11
    - iphone-ios_12
    - iphone-ios_13
    - iphone-ios_14
    - iphone-ios_15
    - iphone-ios_16
    - iphone-ios_17
  jquery-color:
    - chrome_116
    - chrome_117
    #- android_12
    - edge_18
    - edge_108
    - edge_109
    - firefox_115
    - firefox_116
    - firefox_117
    - ie_9
    - ie_10
    - ie_11
    - opera_102
    - safari_16
    - safari_17
    - iphone-ios_15
    - iphone-ios_16
    - iphone-ios_17
  jquery-color-2:
    - chrome_116
    - chrome_117
    #- android_12
    - edge_18
    - edge_115
    - edge_116
    - firefox_48
    - firefox_60
    - firefox_78
    - firefox_91
    - firefox_102
    - firefox_115
    - firefox_116
    - firefox_117
    - ie_6
    - ie_7
    - ie_8
    - ie_9
    - ie_10
    - ie_11
    - opera_102
    - safari_5_1
    - safari_6
    - safari_8
    - safari_9
    - safari_10
    - safari_11
    - safari_12
    - safari_13
    - safari_14
    - safari_15
    - safari_16
    - safari_17
    - iphone-ios_8_3
    - iphone-ios_9_3
    - iphone-ios_10
    - iphone-ios_11
    - iphone-ios_12
    - iphone-ios_13
    - iphone-ios_14
    - iphone-ios_15
    - iphone-ios_16
    - iphone-ios_17
  jquery-ui:
    - chrome_116
    - chrome_117
    - edge_18
    - edge_115
    - edge_116
    - firefox_116
    - firefox_117
    - ie_11
    - opera_101
    - opera_102
    - safari_16
    - safari_17
  jquery-ui-future:
    - chrome_116
    - chrome_117
    - edge_115
    - edge_116
    - firefox_116
    - firefox_117
    - ie_11
    - opera_101
    - opera_102
    - safari_16
    - safari_17
  debug:
    - ie_11
