profile::certbot::certificates:
  blogs:
    domains:
      - "%{::facts.fqdn}"

profile::wordpress::blogs::admin_email: infrastructure-team@jquery.com
profile::wordpress::blogs::sites:
  jqueryui:
    host: blog.jqueryui.com
    site_name: jQuery UI Blog
    certificate: blogs
