profile::certbot::certificates:
  blogs:
    domains:
      - "%{::facts.fqdn}"

profile::wordpress::blogs::admin_email: infrastructure-team@jquery.com
profile::wordpress::blogs::sites:
  jqueryui:
    host: blog.jqueryui.com
    site_name: jQuery UI Blog
    active_theme: jqueryui.com
    certificate: blogs
    # for whatever reason, the jqueryui blog has a different URL structure
    # compared to other blogs have
    permalink_structure: '/%year%/%monthnum%/%postname%/'
