profile::base::enabled_groups: [gitpuppet]

profile::certbot::certificates:
  puppet:
    domains:
      - "%{::facts.fqdn}"

profile::puppet::puppetdb::nginx_certificate_name: puppet
profile::notifier::tls_key_name: puppet
